# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01ae34c064d9f0200edd8d798f87ad9f4747b3939de0ca49cb644ae9e89c95e42e9c300eb0097beec3c0eaba0554d2bd935587aa26e1d0331724e1d7732fdfd8

test:
  secret_key_base: 8b6a0d1470286c94b91000d2801969964ef92af5f0501a4c6a1e25f81da02abe036a41cc0c73ca3a75d37cd46cb29b9db59d91cc104ba5ea083f5bb326170775

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
